# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc 'Prepare new version on develop'
  lane :prepare_new_version do |_options|
    increment_version_code(
      gradle_file_path: 'app/build.gradle'
    )
  end

  desc 'Run Firebase Internal Distribution'
  lane :publish_on_firebase do
    gradle(task: "clean")
    gradle(task: 'assemble', build_type: 'debug', flags: "--stacktrace")
    firebase_app_distribution(
        service_credentials_file: "google-services.json",
        apk_path:'app/build/outputs/apk/debug/app-debug.apk',
        app: ENV['FASTLANE_FIREBASE_ANDROID_APP_ID'],
        groups: "useblu-android-testers"
    )
  end
end
