internal object Versions {
    const val classpathGradleVersion = "8.0.2"
    const val classpathKotlinGradleVersion = "1.8.22"
    const val constraintLayoutVersion = "2.1.4"
    const val lifecycleExtensionsVersion = "2.2.0"
    const val lifecycleViewModelVersion = "2.6.1"
    const val androidKtxVersion = "1.9.0"
    const val androidAppCompatVersion = "1.6.1"
    const val skydovesBalloonVersion = "1.5.2"
    const val androidMaterialVersion = "1.8.0"
    const val canarinhoVersion = "2.0.2"
    const val glideVersion = "4.15.1"
    const val circleIndicatorVersion = "2.1.6"
    const val imageCarouselVersion = "2.0.4"
    const val expansionPanelVersion = "1.2.4"
    const val toggleButtonLayoutVersion = "1.3.0"
    const val calendarViewVersion = "2.0.1"
    const val mpChartVersion = "v3.1.0"
    const val skeletonBonesVersion = "v1.4.5"
    const val skydovesLandscapistVersion = "2.2.2"
    const val composeBOMVersion = "2023.06.01"
    const val activityComposeVersion = "1.7.2"
}