name: baseline-profile

run-name: ${{ github.actor }} requested a workflow

on:
  workflow_dispatch:

jobs:
  generate-baseline-profile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'

      - name: Generate baseline profiles
        run: |
          ./gradlew cleanManagedDevices --unused-only
          ./gradlew clean :ocean-components:generateBaselineProfile -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile -Pandroid.experimental.testOptions.managedDevices.setupTimeoutMinutes=20 -Dorg.gradle.workers.max=4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Generate baseline profile"
          title: "Generate baseline profile"
          delete-branch: true
          branch: actions/baseline-profile